
services:
  sonarqube:
    image: sonarqube:10.6-community
    ports:
      - '9000:9000'
    stop_grace_period: 60m
    healthcheck:
      test: ['CMD-SHELL', 'curl -f http://localhost:9000/ > /dev/null']
      interval: 5s
      timeout: 2s
      retries: 5
      start_period: 5s
    volumes:
      - './data:/opt/sonarqube/data:rw'
      - './extensions:/opt/sonarqube/extensions:rw'
      - './logs:/opt/sonarqube/logs:rw'
